import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import java.util.*;
import java.util.ArrayList;
import static java.util.Collections.list;

/**
 *
 * @author chealyTahir
 */
public class HashMap_Database_UI extends javax.swing.JFrame {

    /**
     * Creates new form HashMap_Database_UI
     */
    public HashMap_Database_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Print_Btn = new javax.swing.JButton();
        cCourse_txt = new javax.swing.JTextField();
        cUnit_txt = new javax.swing.JTextField();
        AddCourse_Btn = new javax.swing.JButton();
        studentID_txt = new javax.swing.JTextField();
        studentName_txt = new javax.swing.JTextField();
        AddStudent_Btn = new javax.swing.JButton();
        majorName_txt = new javax.swing.JTextField();
        majorCourse_txt = new javax.swing.JTextField();
        AddMajor_Btn = new javax.swing.JButton();
        professorID_txt = new javax.swing.JTextField();
        AddProfessor_Btn = new javax.swing.JButton();
        professorName_txt = new javax.swing.JTextField();
        Clear_Btn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HashMap_Database_UI");

        jLabel1.setText("Course");

        jLabel2.setText("Student");

        jLabel3.setText("Major");

        jLabel4.setText("Professor");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Print_Btn.setText("Print");
        Print_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Print_BtnMouseClicked(evt);
            }
        });

        cCourse_txt.setText("enter course name");

        cUnit_txt.setText("enter course units");

        AddCourse_Btn.setText("AddCourse");
        AddCourse_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddCourse_BtnMouseClicked(evt);
            }
        });

        studentID_txt.setText("enter ID");

        studentName_txt.setText("enter student name");

        AddStudent_Btn.setText("AddStudent");
        AddStudent_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddStudent_BtnMouseClicked(evt);
            }
        });

        majorName_txt.setText(" enter major name");

        majorCourse_txt.setText("enter course name");

        AddMajor_Btn.setText("AddMajor");
        AddMajor_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMajor_BtnMouseClicked(evt);
            }
        });

        professorID_txt.setText("professor ID");

        AddProfessor_Btn.setText("AddProfessor");
        AddProfessor_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddProfessor_BtnMouseClicked(evt);
            }
        });

        professorName_txt.setText("professor name");

        Clear_Btn.setText("Clear");
        Clear_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Clear_BtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(studentID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(studentName_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cCourse_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cUnit_txt))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(majorName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(professorID_txt)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(majorCourse_txt)
                                .addComponent(professorName_txt))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddProfessor_Btn)
                    .addComponent(AddCourse_Btn)
                    .addComponent(Print_Btn)
                    .addComponent(AddStudent_Btn)
                    .addComponent(AddMajor_Btn)
                    .addComponent(Clear_Btn))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cCourse_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddCourse_Btn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(cUnit_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddStudent_Btn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(majorName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(majorCourse_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddMajor_Btn))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(professorID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddProfessor_Btn)
                        .addComponent(professorName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Print_Btn)
                        .addGap(27, 27, 27)
                        .addComponent(Clear_Btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCourse_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddCourse_BtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddCourse_BtnMouseClicked

    private void AddStudent_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddStudent_BtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStudent_BtnMouseClicked

    private void AddMajor_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMajor_BtnMouseClicked
        // TODO add your handling code here:
        String majorCourse = "";
        String pre_majorName = "";
        String majorName = "";
        ArrayList<String> course_Arraylist = new ArrayList();
        Major majorObject = new Major();
        hashmapDatabase hashmapObject = new hashmapDatabase();
    while(majorName == pre_majorName) {    
        if(majorName_txt.getText().length() !=0) {
            majorName = majorName_txt.getText();
            pre_majorName = majorName;
                majorObject.set_majorName(majorName);
                if (majorCourse_txt.getText().length() != 0) {
                    majorCourse = majorCourse_txt.getText();
                    course_Arraylist.add(majorCourse);
                    System.out.println(majorObject.get_majorName());
                    System.out.println(majorObject.get_courseName());
                    jTextArea1.append(majorName+": " + majorCourse + "\n");
                }
                else {
                    jTextArea1.append(majorName+"\n");
                }
                majorCourse_txt.setText(""); 
                majorName = majorName_txt.getText();           
        }
    }
            for (String course : course_Arraylist) {
                System.out.print(course + " ");
                majorObject.add_MajorCourse(course);
            } 
            System.out.println();
            hashmapObject.add_major_Hashmap(majorObject);
            System.out.println("Print all major from Database.");
            hashmapObject.print_major_Hashmap();
            System.out.println();
    }//GEN-LAST:event_AddMajor_BtnMouseClicked

    private void AddProfessor_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddProfessor_BtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProfessor_BtnMouseClicked

    private void Print_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Print_BtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Print_BtnMouseClicked

    private void Clear_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Clear_BtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Clear_BtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HashMap_Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HashMap_Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HashMap_Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HashMap_Database_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HashMap_Database_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCourse_Btn;
    private javax.swing.JButton AddMajor_Btn;
    private javax.swing.JButton AddProfessor_Btn;
    private javax.swing.JButton AddStudent_Btn;
    private javax.swing.JButton Clear_Btn;
    private javax.swing.JButton Print_Btn;
    private javax.swing.JTextField cCourse_txt;
    private javax.swing.JTextField cUnit_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField majorCourse_txt;
    private javax.swing.JTextField majorName_txt;
    private javax.swing.JTextField professorID_txt;
    private javax.swing.JTextField professorName_txt;
    private javax.swing.JTextField studentID_txt;
    private javax.swing.JTextField studentName_txt;
    // End of variables declaration//GEN-END:variables
}
